import type { TestCase, WaterParameter } from './types';

export const initialWaterParameters: WaterParameter[] = [
  {
    id: 'ph',
    name: 'pH Value',
    symbol: 'pH',
    standard: 'BIS 10500',
    idealRange: 'Ideal range: 6.5 – 8.5',
    currentValue: '7.2',
    unit: '',
    status: 'Good',
    progressPercentage: 72,
    colorScheme: 'teal',
  },
  {
    id: 'turbidity',
    name: 'Turbidity (Clarity)',
    symbol: '⊟',
    standard: 'Standard: < 5 NTU',
    idealRange: 'Standard: < 5 NTU',
    currentValue: '1.8',
    unit: 'NTU',
    status: 'Good',
    progressPercentage: 36,
    colorScheme: 'teal',
  },
  {
    id: 'nitrate',
    name: 'Nitrate (NO₃)',
    symbol: 'N',
    standard: 'Standard: < 45 mg/L',
    idealRange: 'Standard: < 45 mg/L',
    currentValue: '8.0',
    unit: 'mg/L',
    status: 'Good',
    progressPercentage: 18,
    colorScheme: 'teal',
  },
  {
    id: 'chlorine',
    name: 'Residual Chlorine',
    symbol: 'Cl',
    standard: 'Ideal: 0.2 – 1.0 mg/L',
    idealRange: 'Ideal: 0.2 – 1.0 mg/L',
    currentValue: '0.4',
    unit: 'mg/L',
    status: 'Good',
    progressPercentage: 40,
    colorScheme: 'teal',
  },
  {
    id: 'bacteria',
    name: 'Coliform Bacteria (E. coli)',
    symbol: '🦠',
    standard: 'Must be: 0 per 100 mL',
    idealRange: 'Must be: 0 per 100 mL',
    currentValue: 'Not Detected',
    unit: '',
    status: 'Safe',
    progressPercentage: 0,
    colorScheme: 'emerald',
  },
];

export const initialCases: TestCase[] = [
  {
    id: 'CASE-2025-089',
    sourceId: 'RS-1043',
    sourceName: 'Patel Nagar Hand Pump',
    location: 'Kalyanpur Village, Ward 4',
    district: 'Riverside District, Uttar Pradesh',
    reportedAt: '2 hours ago',
    reportedTimestamp: Date.now() - 2 * 3600 * 1000,
    deadlineHours: 22,
    deadlineLabel: '22h left (Turnaround target: 24h)',
    status: 'review_needed',
    confidence: 96.4,
    stripAlignment: 'good',
    lighting: 'good',
    clarity: 'good',
    operator: {
      id: 'OP-402',
      name: 'Sunita Devi (JJM Volunteer)',
      role: 'Certified FTK Field Tester',
      phone: '+91 98765 43210',
    },
    flags: [
      {
        parameter: 'Residual Free Chlorine',
        value: '0.05 mg/L',
        standard: 'Min 0.2 mg/L required for disinfection',
        severity: 'warning',
      },
      {
        parameter: 'Turbidity',
        value: '5.8 NTU',
        standard: 'Permissible limit max 5.0 NTU',
        severity: 'danger',
      },
    ],
    observations: {
      odour: 'No odour (Agreeable)',
      turbidity: 'Slightly Hazy (5.8 NTU)',
      residualChlorine: 0.05,
      sanitaryRemarks: 'Cracked platform drainage apron, stagnant pool 1.5m away.',
    },
    gps: {
      lat: 25.6124,
      lng: 81.8432,
      accuracy: '±3m',
    },
    auditTrail: [
      {
        id: 'aud-1',
        timestamp: 'Today, 07:30 AM',
        actor: 'Sunita Devi (OP-402)',
        action: 'Field sample captured via JalSakshi FTK Mobile Assistant.',
        type: 'creation',
        notes: 'AI optical verification: Strip aligned, illumination optimal, confidence 96.4%.',
      },
      {
        id: 'aud-2',
        timestamp: 'Today, 07:32 AM',
        actor: 'JalSakshi Cloud Engine',
        action: 'Case flagged: Low residual chlorine (<0.2 mg/L) & Elevated Turbidity.',
        type: 'creation',
        notes: 'CAG SLA Timer initiated: 24 hours to laboratory referral assignment.',
      },
    ],
  },
  {
    id: 'CASE-2025-084',
    sourceId: 'RS-2099',
    sourceName: 'Shanti Nagar Borewell',
    location: 'Near Primary Health Center, Block B',
    district: 'Riverside District, Uttar Pradesh',
    reportedAt: '14 hours ago',
    reportedTimestamp: Date.now() - 14 * 3600 * 1000,
    deadlineHours: 10,
    deadlineLabel: '10h remaining (Lab SLA critical)',
    status: 'awaiting_lab',
    confidence: 89.1,
    stripAlignment: 'good',
    lighting: 'fair',
    clarity: 'good',
    operator: {
      id: 'OP-118',
      name: 'Rameshwar Kumar',
      role: 'Gram Panchayat Water Secretary',
      phone: '+91 94150 11223',
    },
    flags: [
      {
        parameter: 'pH Value',
        value: '5.5 (Acidic)',
        standard: 'Permissible 6.5 – 8.5',
        severity: 'danger',
      },
    ],
    observations: {
      odour: 'Slight metallic smell',
      turbidity: 'Clear (< 1 NTU)',
      residualChlorine: 0.3,
      sanitaryRemarks: 'Iron casing showing oxidation signs.',
    },
    gps: {
      lat: 25.6311,
      lng: 81.8102,
      accuracy: '±4m',
    },
    labDetails: {
      labName: 'Sub-Divisional Water Quality Testing Laboratory, Sadar',
      assignedAt: 'Yesterday, 04:15 PM',
      turnaroundTarget: '48 Hours (Standard JJM Lab Protocol)',
      reportNumber: 'NABL-WQ-2025-9912',
      isVerified: false,
    },
    auditTrail: [
      {
        id: 'aud-3',
        timestamp: 'Yesterday, 02:00 PM',
        actor: 'Rameshwar Kumar (OP-118)',
        action: 'Field sample uploaded with pH 5.5 colorimetric screening.',
        type: 'creation',
      },
      {
        id: 'aud-4',
        timestamp: 'Yesterday, 04:15 PM',
        actor: 'Dr. A. K. Sharma (District Supervisor)',
        action: 'Referred to Sadar Sub-Divisional Laboratory for NABL confirmation.',
        type: 'assignment',
        notes: 'Physical sample collection transit container QR: TRANSIT-4491.',
      },
    ],
  },
  {
    id: 'CASE-2025-072',
    sourceId: 'RS-3102',
    sourceName: 'Govt. Primary School Tube Well',
    location: 'Govt. Primary School, Sector 4',
    district: 'Riverside District, Uttar Pradesh',
    reportedAt: '1 day ago',
    reportedTimestamp: Date.now() - 30 * 3600 * 1000,
    deadlineHours: -6,
    deadlineLabel: 'OVERDUE by 6 hours',
    status: 'action_required',
    confidence: 99.0,
    stripAlignment: 'good',
    lighting: 'good',
    clarity: 'good',
    operator: {
      id: 'OP-305',
      name: 'Pooja Verma (ASHA Worker)',
      role: 'Community Health Volunteer',
      phone: '+91 97920 33445',
    },
    flags: [
      {
        parameter: 'Nitrate (NO₃)',
        value: '58.0 mg/L',
        standard: 'BIS Maximum Safe Limit 45 mg/L',
        severity: 'danger',
      },
      {
        parameter: 'Coliform (E. coli)',
        value: '12 CFU / 100 mL',
        standard: 'Zero tolerance (0 CFU)',
        severity: 'danger',
      },
    ],
    observations: {
      odour: 'Disagreeable earthy odour',
      turbidity: 'Turbid (6.2 NTU)',
      residualChlorine: 0.0,
      sanitaryRemarks: 'Septic tank soak pit within 8m radius.',
    },
    gps: {
      lat: 25.5901,
      lng: 81.8654,
      accuracy: '±2m',
    },
    labDetails: {
      labName: 'District Central Water Testing Lab, JJM Campus',
      assignedAt: '2 days ago',
      turnaroundTarget: '24 Hours',
      reportNumber: 'NABL-REP-2025-4421',
      verifiedResult: 'Nitrate 58.0 mg/L & E.coli 12 CFU/100ml confirmed (Failed).',
      verifiedBy: 'Senior Microbiologist Dr. V. Sen',
      isVerified: true,
    },
    remediation: {
      actionPlan: 'Immediate source isolation, emergency super-chlorination & sanitary seal repair.',
      assignedTo: 'Jal Nigam Executive Engineer (Rural Circle)',
      accepted: false,
    },
    auditTrail: [
      {
        id: 'aud-5',
        timestamp: '2 days ago',
        actor: 'Pooja Verma',
        action: 'FTK Screening identified severe nitrate contamination.',
        type: 'creation',
      },
      {
        id: 'aud-6',
        timestamp: 'Yesterday, 10:00 AM',
        actor: 'District Central Water Testing Lab',
        action: 'Lab confirmed contamination (E. coli 12 CFU, Nitrate 58 mg/L).',
        type: 'lab',
        notes: 'Notice served to School Management Committee to cease drinking use immediately.',
      },
      {
        id: 'aud-7',
        timestamp: 'Yesterday, 02:30 PM',
        actor: 'Supervisor Portal',
        action: 'Remediation Order Dispatched to Jal Nigam Rural Team.',
        type: 'action',
      },
    ],
  },
  {
    id: 'CASE-2025-061',
    sourceId: 'RS-0914',
    sourceName: 'Market Square Standpost Tap',
    location: 'Weekly Market Grounds, Haat Road',
    district: 'Riverside District, Uttar Pradesh',
    reportedAt: '3 days ago',
    reportedTimestamp: Date.now() - 72 * 3600 * 1000,
    deadlineHours: 48,
    deadlineLabel: 'Retest Due in 48h',
    status: 'retest_due',
    confidence: 97.2,
    stripAlignment: 'good',
    lighting: 'good',
    clarity: 'good',
    operator: {
      id: 'OP-402',
      name: 'Sunita Devi',
      role: 'Certified FTK Field Tester',
      phone: '+91 98765 43210',
    },
    flags: [
      {
        parameter: 'Turbidity',
        value: '7.1 NTU (Remediated to 1.2 NTU)',
        standard: 'Max 5.0 NTU',
        severity: 'warning',
      },
    ],
    observations: {
      odour: 'No odour',
      turbidity: 'Previously turbid due to pipeline rupture',
      residualChlorine: 0.5,
      sanitaryRemarks: 'Main pipeline replacement completed by PHED crew.',
    },
    gps: {
      lat: 25.6045,
      lng: 81.8312,
      accuracy: '±3m',
    },
    remediation: {
      actionPlan: 'Replaced 40m corroded GI supply line & flushed standpost.',
      assignedTo: 'PHED Maintenance Gang #3',
      completedAt: 'Yesterday, 05:00 PM',
      evidenceNotes: 'Replacement photo and pressure test certificate uploaded.',
      accepted: true,
    },
    retest: {
      scheduledDate: 'Tomorrow, 09:00 AM',
      isPassed: false,
    },
    auditTrail: [
      {
        id: 'aud-8',
        timestamp: '3 days ago',
        actor: 'Sunita Devi',
        action: 'Reported pipeline rupture and turbidity spike.',
        type: 'creation',
      },
      {
        id: 'aud-9',
        timestamp: 'Yesterday, 05:00 PM',
        actor: 'PHED Junior Engineer',
        action: 'Physical repair completed and certified.',
        type: 'action',
      },
      {
        id: 'aud-10',
        timestamp: 'Today, 08:00 AM',
        actor: 'Supervisor Portal',
        action: 'Retest job automatically dispatched to local field volunteer.',
        type: 'retest',
      },
    ],
  },
  {
    id: 'CASE-2025-055',
    sourceId: 'RS-0421',
    sourceName: 'Anand Vihar Community Well',
    location: 'Anand Vihar Ward 2',
    district: 'Riverside District, Uttar Pradesh',
    reportedAt: '5 days ago',
    reportedTimestamp: Date.now() - 120 * 3600 * 1000,
    deadlineHours: 0,
    deadlineLabel: 'Ready for Closure Approval',
    status: 'closure_review',
    confidence: 98.6,
    stripAlignment: 'good',
    lighting: 'good',
    clarity: 'good',
    operator: {
      id: 'OP-201',
      name: 'Mohan Lal',
      role: 'Village Water Committee Member',
      phone: '+91 94155 66778',
    },
    flags: [
      {
        parameter: 'Fluoride',
        value: '1.9 mg/L (Normalized to 0.8 mg/L)',
        standard: 'Permissible limit 1.0 – 1.5 mg/L',
        severity: 'danger',
      },
    ],
    observations: {
      odour: 'Agreeable',
      turbidity: 'Clear',
      residualChlorine: 0.4,
      sanitaryRemarks: 'Community defluoridation unit resin bed recharged.',
    },
    gps: {
      lat: 25.6289,
      lng: 81.8491,
      accuracy: '±2m',
    },
    labDetails: {
      labName: 'State Central Public Health Lab',
      assignedAt: '5 days ago',
      turnaroundTarget: '48h',
      reportNumber: 'NABL-FL-2025-8819',
      verifiedResult: 'Fluoride confirmed at 1.9 mg/L initially.',
      isVerified: true,
    },
    remediation: {
      actionPlan: 'Activated Alumina defluoridation plant media replenishment.',
      assignedTo: 'District JJM Technical Cell',
      completedAt: '2 days ago',
      evidenceNotes: 'Media replacement voucher #MV-901 and flow rate test attached.',
      accepted: true,
    },
    retest: {
      scheduledDate: 'Yesterday, 11:30 AM',
      retestSampleId: 'SMP-2025-9988',
      result: 'Fluoride 0.8 mg/L, pH 7.4 (Fully Passed BIS 10500 standards).',
      isPassed: true,
    },
    auditTrail: [
      {
        id: 'aud-11',
        timestamp: '5 days ago',
        actor: 'Mohan Lal',
        action: 'Flagged elevated fluoride during monthly surveillance.',
        type: 'creation',
      },
      {
        id: 'aud-12',
        timestamp: '2 days ago',
        actor: 'JJM Technical Cell',
        action: 'Alumina defluoridation filter media replenished.',
        type: 'action',
      },
      {
        id: 'aud-13',
        timestamp: 'Yesterday, 11:30 AM',
        actor: 'Sunita Devi (OP-402)',
        action: 'Follow-up retest verified parameter at 0.8 mg/L.',
        type: 'retest',
      },
    ],
  },
];
